name: Deploy HawkBot to EC2

on:
  push:
    branches: [ test ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST_NAME: ec2-34-230-72-42.compute-1.amazonaws.com
        USER_NAME: ec2-user
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} '
          # Update system
          sudo yum update -y

          # Install Python if not already installed
          sudo yum install python3 python3-pip -y

          # Install virtualenv
          sudo pip3 install virtualenv

          # Navigate to project directory (adjust path as needed)
          cd hawkBot/HawkBot/server

          # Create and activate virtual environment if it doesn't exist
          [ ! -d "venv" ] && python3 -m venv venv
          source venv/bin/activate

          # Pull latest code from test branch
          git pull origin test

          # Install or upgrade pip
          pip install --upgrade pip

          # Install project dependencies
          pip install -r requirements.txt

          # Run migrations
          python manage.py migrate

          # Collect static files (if you're serving static files)
          python manage.py collectstatic --noinput

          
          

          echo "Deployment completed"
        '